In [1]:
import numpy as np

def inv_matrix(A):
    """Inversión de una matriz cuadrada mediante método de Gauss-Jordan."""
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)
    n = A.shape[0]
    assert A.shape[0] == A.shape[1], "La matriz debe ser cuadrada."
    I = np.eye(n)
    Ab = np.hstack((A, I))
    for i in range(n):
        p = None
        for pi in range(i, n):
            if Ab[pi, i] != 0:
                p = pi
                break
        if p is None:
            raise ValueError("No existe solución única.")
        if p != i:
            Ab[[i, p], :] = Ab[[p, i], :]
        Ab[i, :] = Ab[i, :] / Ab[i, i]
        for j in range(n):
            if j != i:
                Ab[j, :] = Ab[j, :] - Ab[j, i] * Ab[i, :]
    return Ab[:, n:]

# Ejercicio 1
A1 = [[2, -3], [-1, 1]]
print('Inversa de A1:')
print(inv_matrix(A1))

# Ejercicio 2
A2 = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]
print('Inversa de A2:')
print(inv_matrix(A2))

Inversa de A1:
[[-1. -3.]
 [-1. -2.]]
Inversa de A2:
[[-36.  45.  60. -80.]
 [  3.  -4.  -5.   7.]
 [  9. -11. -15.  20.]
 [ 29. -36. -48.  64.]]
